name: paulinserra
favicon: null
layout_spectrum: 0.26341373170726
typography_spectrum: 0.61007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d96d24'
    - '#aa4f1f'
    - '#723110'
    - '#e79a57'
    - '#dfbb76'
  brandStrength: 0.6887474644463509
  lightness: 0.009530208772048354
  saturation: 0.8618606224190444
  rhythmicContrast: 0.1026500528678298
purpose: []
